### ISSUE TITLE
The `--spa` is responding html for any type of request (e.g. js/css)

### ISSUE THREAD

**Issue by Huxpro** [marijnh/moduleserve#12]
![image](https://user-images.githubusercontent.com/5563315/94375960-2d673900-00cc-11eb-9913-7568d1a00a69.png)

The `--spa` option is not very usable in that it will always respond the index html file for any type of requests e.g. js and css. 

You can repro with my demo at https://github.com/Huxpro/githuber.re-v2 by:
1. `npm install && npm run start` and in another tab: `npm run dev`.
2. search some github user (e.g. marijnh) to make router changes the URL.
3. refresh and observe similar errors in console or network panel of browser devtools.

**Comment by marijnh** [comment]
That's what it's documented to do. I'm not too sure what its point is either (it was contributed via a PR), but well, just don't enable it if you don't want this behavior.
