### ISSUE TITLE
Techniques for accessing modules directly

### ISSUE THREAD

**Issue by ericandrewlewis** [marijnh/moduleserve#4]
I wanted to have access to modules directly, so I can access them in the browser JS console and play around.

I exposed [`var loaded`](https://github.com/marijnh/moduleserve/blob/master/client.js#L12) onto `window.LoadedModules`, so I can access modules directly via their relative path.

e.g. 

``` js
LoadedModules["/../dist/format/index"].parseFrom( LoadedModules["/../dist/model/defaultschema"].defaultSchema, "* test*", "markdown" )
```

I also ended up exposing [the root module](https://github.com/marijnh/moduleserve/blob/master/client.js#L60), so I can load other modules on the fly via `mainModule.require( "/../dist/markdown" )`

Not really suggesting any changes, just sharing what I'm doing.

**Comment by marijnh** [comment]
That's a good suggestion. I've pushed a patch that allows you to set a `data-require` attribute on your script tag to optionally export `require` to the top scope. I don't think you need access to `LoadedModules` if you have `require`. Do you agree?

**Comment by ericandrewlewis** [comment]
> I don't think you need access to LoadedModules if you have require. Do you agree?

Totally. Cool commit!
